<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Vehicles\Exceptions\" />
    <Folder Include="Vehicles\Repositories\" />
    <Folder Include="Spots\Exceptions\" />
    <Folder Include="Reservations\Exceptions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MailKit" Version="4.10.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="MimeKit" Version="4.10.0" />
    <PackageReference Include="Scrutor" Version="6.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParkingHere.Domain\ParkingHere.Domain.csproj" />
  </ItemGroup> 
	
</Project>
